### ISSUE TITLE
Cant Login to admin page after setup

### ISSUE THREAD

**Issue by AndrewHuddleston** [goksan/statusnook#7]
Go through the setup, set the website, admin username and password, page name. All successful. Go to enter the admin username and password to login to the admin page. "Incorrect Credentials" 

Ran through the setup 3 times same result and its not the wrong password. Also tried chrome and safari same result.

Setup:
- Docker compose
- Ubuntu 

```
 statusnook:
    ports:
      - 8000:8000
    volumes:
      - /mnt/configs/statusnook:/app/statusnook-data
    restart: always
    container_name: statusnook
    image: goksan/statusnook
 ```
